### ISSUE TITLE
Extracting valuenum instead of value

### ISSUE THREAD

**Issue by RotemSap** [MLforHealth/MIMIC_Extract#37]
First let me start with thanking you for the amazing work and latest updates.

I came up with a problem regarding the extraction of the "vitals_labs" (X dataframe), after trying to extract a feature that has text in his "value" column, but a number in his "valuenum" column inside "chartevents" table.

My question is why did you decide to extract the values inside the "value" column and not the "valuenum"? 
And if by changing the "save_numerics" function I could extract the "valuenum" data without sabotage the DF\CODE\DATA?

Thank you

**Comment by mmcdermott** [comment]
@tnaumann @mghassem @michaelchughes Can you offer some historical context here regarding why the `value` column was used initially rather than the `valuenum` column?

Additionally, @RotemSap, yes, I think you should be able to modify the save_numerics function (really I think you'd just need to modify the SQL query above save_numerics and keep the column named "value" in the output) without downstream issues. Though, I'd wait for commentary from the folks listed above as to why `value` was used instead of `valuenum` before doing that.

**Comment by mmcdermott** [comment]
@RotemSap, I've connected with some folks off-thread who have more historical knowledge, and the recollection is that the the valuenum column used to be poorly populated, but now it may be a better target, as you suggest. I'll file another issue to track us shifting to use that column, but to be transparent I'm not sure off-hand when we'll get to it -- if you end up modifying the code yourself to point at that column and submit a PR, we'll definitely be grateful, of course, and either way we should get to it eventually. Please feel free to re-open this if you have further questions.
