### ISSUE TITLE
Question about removing variables with high missing values

### ISSUE THREAD

**Issue by ducnx** [MLforHealth/MIMIC_Extract#42]
From your extraction script, by specifying `min_percent`, we can exclude variables with high proportions of missing values. However,  in the [code](https://github.com/MLforHealth/MIMIC_Extract/blob/50b3077778f580bb110669541c054fe95ec41612/mimic_direct_extract.py#L314-L321), when you remove columns before spliting into train/test set, does it mean you leak information from the test set to the train set? I think a correct setting should be using the train data to find columns with high missing percentage, then filter out those columns from the test set.
Anyway, I think it's just a minor detail. I just want to hear the opinion from your side.

**Comment by mmcdermott** [comment]
Yes, you are correct in that we remove columns before splitting into the train/test set, and yes, I agree that this does constitute a (minor) case of leakage from the train to the test set. You can easily avoid this by simply setting `min_percent` to 0 and doing the filtering manually after the train/test split in the output, though this is obviously less elegant.

Right now, we don't do any official train/test split in our extraction, which is why we don't address this. I think it is also the case that (under a random-per-patient split) this is unlikely to be a serious source of leakage given the data size.

That said, this definitely warrants better messaging in our documentation (which I did in https://github.com/MLforHealth/MIMIC_Extract/commit/420bfc4122cd267ae92c2934fb4f49dcc2aed577)! Great catch, thanks for letting us know.
