### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by corcra** [MLforHealth/MIMIC_Extract#51]
Is there a plan to continue developing this library, and if yes are community contributions welcomed or accommodated?

**Comment by bnestor** [comment]
Yeah we want to mostly move on to mimic-IV, but that involves switching some queries from PostgreSQL to BigQuery amongst other things. There is room to contribute here if you want to submit PRs. For MIMIC-IV there will be lots of places to contribute because there is more data (I think the entire patient stay before and after ICU is available for example).
